// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Torneos.Api.Data;

#nullable disable

namespace Torneos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219174424_InitialCore")]
    partial class InitialCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Equipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Partido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("integer");

                    b.Property<long>("LocalEquipoId")
                        .HasColumnType("bigint");

                    b.Property<long>("TorneoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VisitanteEquipoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("LocalEquipoId");

                    b.HasIndex("TorneoId");

                    b.HasIndex("VisitanteEquipoId");

                    b.ToTable("Partidos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Torneo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Torneos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TorneoEquipo", b =>
                {
                    b.Property<long>("TorneoId")
                        .HasColumnType("bigint");

                    b.Property<long>("EquipoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TorneoId", "EquipoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TorneoId");

                    b.ToTable("TorneosEquipos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Partido", b =>
                {
                    b.HasOne("Domain.Entities.Equipo", "LocalEquipo")
                        .WithMany("PartidosComoLocal")
                        .HasForeignKey("LocalEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Torneo", "Torneo")
                        .WithMany("Partidos")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Equipo", "VisitanteEquipo")
                        .WithMany("PartidosComoVisitante")
                        .HasForeignKey("VisitanteEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocalEquipo");

                    b.Navigation("Torneo");

                    b.Navigation("VisitanteEquipo");
                });

            modelBuilder.Entity("Domain.Entities.TorneoEquipo", b =>
                {
                    b.HasOne("Domain.Entities.Equipo", "Equipo")
                        .WithMany("TorneosEquipos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Torneo", "Torneo")
                        .WithMany("TorneosEquipos")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Domain.Entities.Equipo", b =>
                {
                    b.Navigation("PartidosComoLocal");

                    b.Navigation("PartidosComoVisitante");

                    b.Navigation("TorneosEquipos");
                });

            modelBuilder.Entity("Domain.Entities.Torneo", b =>
                {
                    b.Navigation("Partidos");

                    b.Navigation("TorneosEquipos");
                });
#pragma warning restore 612, 618
        }
    }
}
